sudo: required
language: python
dist: xenial
services:
  - docker
python:
  - '3.6'
node_js:
  - 'node'
install:
  - sudo apt-get install ffmpeg && ffmpeg -version
  - npm i
  - pip install pipenv && pipenv --version
  - pipenv install --system --deploy
  - pip install coverage && coverage --version
cache:
  - pip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run build
  - export PYTHONPATH=lib
  - coverage run -m pytest ./tests && coverage report
  - docker build .
after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  apt:
    update: true
