sudo: required
language: python
dist: xenial
services:
  - docker
python:
  - "3.6"
  - "3.7-dev"
node_js:
  - "node"
install:
  - sudo apt-get install ffmpeg && ffmpeg -version
  - pip install coverage poetry
  - poetry config virtualenvs.in-project true
  - make
  - . ./.venv/bin/activate
  - export NODE_ENV=production
  - export PYTHONPATH=server
cache:
  - pip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - docker build . --build-arg NPM_MIRROR= --build-arg DEBIAN_MIRROR= --build-arg PIP_MIRROR=
  - coverage run -m pytest server && coverage report
after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  apt:
    update: true
