sudo: required
language: python
dist: xenial
services:
  - docker
python:
  - '3.6'
  - '3.7-dev'
node_js:
  - 'node'
install:
  - sudo apt-get install ffmpeg && ffmpeg -version
  - npm i
  - pip install -r requirements.txt
  - pip install coverage && coverage --version
cache:
  - pip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - docker build . --build-arg NPM_MIRROR= --build-arg DEBIAN_MIRROR= --build-arg PIP_MIRROR=
  - export NODE_ENV=production; npm run build
  - export PYTHONPATH=server
  - coverage run -m pytest ./server/tests && coverage report
after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  apt:
    update: true
